### PR TITLE
[#126417269] Zero-byte file causes Rogers to fail on retrieve and stalls the pipeline

### PR DESCRIPTION
**Pull request by runongirlrunon**
[Tracker #126417269](https://www.pivotaltracker.com/story/show/126417269)

Adds response to the ftp command "SIZE" to the gem.

### CODE REVIEW

**Comment by runongirlrunon** [comment]
@pfarrell

**Review by pfarrell — APPROVED** [review]
This LGTM, demoed locally with rogers spec files

**Comment by soonahn** [comment]
@pfarrell why are we checking the file size on their FTP server, rather than just getting the files and checking the file size locally?

**Comment by runongirlrunon** [comment]
@soonahn we're not actually deciding the functionality of the command, just implementing it based on how real FTP servers respond to it.

**Comment by soonahn** [comment]
@runongirlrunon I'm assuming you're using this command in Rogers to determine the size of a file on the remote host, rather than locally.  If I'm wrong in this assumption, then I'm not quite sure how this PR relates to the story.

**Comment by runongirlrunon** [comment]
@soonahn I'm using it to look at the files on our local server to determine which new files to process. The fix itself is already implemented if you want to take a look at my story branch to see how I'm using it, I just haven't made a PR yet because I need to fix the tests. Hence, here we are.

**Comment by soonahn** [comment]
@runongirlrunon What do you mean by local server?

**Comment by soonahn** [comment]
@runongirlrunon if you mean "local server" as in the Grand Rounds FTP, then that's not what we'd usually refer to as "our local server".  We'd generally refer to that as a remote host, as it's the remote target in our FTP call.

Looking at your code in your branch you are infact implementing this exactly as I was assuming, by looking at the file from the remote host, and doing some logic around that information.

**Comment by soonahn** [comment]
Also, since this is a good clean PR, this is a prime example of a piece of code we can open a PR against the maintainer, and contribute back to the community.

**Comment by runongirlrunon** [comment]
@soonahn I forked it because the original isn't really being maintained and we need this functionality right now, but I will definitely open a PR to the original so that others can see it at least.

**Pull request merged**
